export const LANGUAGES = [
    // European Languages
    { code: 'sq', name: 'Albanian' },
    { code: 'eu', name: 'Basque' },
    { code: 'be', name: 'Belarusian' },
    { code: 'bs', name: 'Bosnian' },
    { code: 'bg', name: 'Bulgarian' },
    { code: 'ca', name: 'Catalan' },
    { code: 'hr', name: 'Croatian' },
    { code: 'cs', name: 'Czech' },
    { code: 'da', name: 'Danish' },
    { code: 'nl', name: 'Dutch' },
    { code: 'en', name: 'English' },
    { code: 'et', name: 'Estonian' },
    { code: 'fi', name: 'Finnish' },
    { code: 'fr', name: 'French' },
    { code: 'gl', name: 'Galician' },
    { code: 'de', name: 'German' },
    { code: 'el', name: 'Greek' },
    { code: 'hu', name: 'Hungarian' },
    { code: 'is', name: 'Icelandic' },
    { code: 'ga', name: 'Irish' },
    { code: 'it', name: 'Italian' },
    { code: 'lv', name: 'Latvian' },
    { code: 'lt', name: 'Lithuanian' },
    { code: 'lb', name: 'Luxembourgish' },
    { code: 'mk', name: 'Macedonian' },
    { code: 'mt', name: 'Maltese' },
    { code: 'no', name: 'Norwegian' },
    { code: 'pl', name: 'Polish' },
    { code: 'pt', name: 'Portuguese' },
    { code: 'ro', name: 'Romanian' },
    { code: 'ru', name: 'Russian' },
    { code: 'sr', name: 'Serbian' },
    { code: 'sk', name: 'Slovak' },
    { code: 'sl', name: 'Slovenian' },
    { code: 'es', name: 'Spanish' },
    { code: 'sv', name: 'Swedish' },
    { code: 'tr', name: 'Turkish' },
    { code: 'uk', name: 'Ukrainian' },
    { code: 'cy', name: 'Welsh' },
    
    // Asian Languages
    { code: 'ar', name: 'Arabic' },
    { code: 'hy', name: 'Armenian' },
    { code: 'az', name: 'Azerbaijani' },
    { code: 'bn', name: 'Bengali' },
    { code: 'my', name: 'Burmese' },
    { code: 'zh', name: 'Chinese (Mandarin)' },
    { code: 'yue', name: 'Chinese (Cantonese)' },
    { code: 'ka', name: 'Georgian' },
    { code: 'gu', name: 'Gujarati' },
    { code: 'he', name: 'Hebrew' },
    { code: 'hi', name: 'Hindi' },
    { code: 'id', name: 'Indonesian' },
    { code: 'ja', name: 'Japanese' },
    { code: 'kn', name: 'Kannada' },
    { code: 'kk', name: 'Kazakh' },
    { code: 'km', name: 'Khmer' },
    { code: 'ko', name: 'Korean' },
    { code: 'ku', name: 'Kurdish' },
    { code: 'lo', name: 'Lao' },
    { code: 'ml', name: 'Malayalam' },
    { code: 'mr', name: 'Marathi' },
    { code: 'mn', name: 'Mongolian' },
    { code: 'ne', name: 'Nepali' },
    { code: 'ps', name: 'Pashto' },
    { code: 'fa', name: 'Persian (Farsi)' },
    { code: 'pa', name: 'Punjabi' },
    { code: 'si', name: 'Sinhala' },
    { code: 'ta', name: 'Tamil' },
    { code: 'te', name: 'Telugu' },
    { code: 'th', name: 'Thai' },
    { code: 'bo', name: 'Tibetan' },
    { code: 'ur', name: 'Urdu' },
    { code: 'uz', name: 'Uzbek' },
    { code: 'vi', name: 'Vietnamese' },
    
    // African Languages
    { code: 'am', name: 'Amharic' },
    { code: 'af', name: 'Afrikaans' },
    { code: 'ha', name: 'Hausa' },
    { code: 'ig', name: 'Igbo' },
    { code: 'rw', name: 'Kinyarwanda' },
    { code: 'mg', name: 'Malagasy' },
    { code: 'ny', name: 'Nyanja (Chichewa)' },
    { code: 'om', name: 'Oromo' },
    { code: 'sn', name: 'Shona' },
    { code: 'so', name: 'Somali' },
    { code: 'st', name: 'Sotho' },
    { code: 'sw', name: 'Swahili' },
    { code: 'ti', name: 'Tigrinya' },
    { code: 'ts', name: 'Tsonga' },
    { code: 'tn', name: 'Tswana' },
    { code: 'xh', name: 'Xhosa' },
    { code: 'yo', name: 'Yoruba' },
    { code: 'zu', name: 'Zulu' },
    
    // Americas Languages
    { code: 'ay', name: 'Aymara' },
    { code: 'gn', name: 'Guarani' },
    { code: 'ht', name: 'Haitian Creole' },
    { code: 'qu', name: 'Quechua' },
    
    // Other Languages
    { code: 'ceb', name: 'Cebuano' },
    { code: 'eo', name: 'Esperanto' },
    { code: 'haw', name: 'Hawaiian' },
    { code: 'hmn', name: 'Hmong' },
    { code: 'iu', name: 'Inuktitut' },
    { code: 'jv', name: 'Javanese' },
    { code: 'la', name: 'Latin' },
    { code: 'ms', name: 'Malay' },
    { code: 'mi', name: 'Maori' },
    { code: 'sm', name: 'Samoan' },
    { code: 'gd', name: 'Scottish Gaelic' },
    { code: 'sd', name: 'Sindhi' },
    { code: 'su', name: 'Sundanese' },
    { code: 'tl', name: 'Tagalog (Filipino)' },
    { code: 'tg', name: 'Tajik' },
    { code: 'tk', name: 'Turkmen' },
    { code: 'ug', name: 'Uyghur' },
    { code: 'yi', name: 'Yiddish' },
].sort((a, b) => a.name.localeCompare(b.name));